2025-08-18 16:46:39,531 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 16:46:43,003 - INFO - Usuario: aux | Rol: auxiliar  | GET /
2025-08-18 16:46:43,056 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:46:43,103 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /static/favicon.svg
2025-08-18 16:46:47,685 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 16:46:47,766 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 16:46:47,771 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 16:46:47,833 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:46:56,596 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:46:56,617 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:47:05,196 - INFO - Usuario: aux | Rol: auxiliar  | POST /
2025-08-18 16:47:05,262 - INFO - Usuario: jefe | Rol: jefe  | GET /home
2025-08-18 16:47:05,306 - INFO - Usuario: jefe | Rol: jefe  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:47:10,379 - INFO - Usuario: jefe | Rol: jefe  | GET /logout
2025-08-18 16:47:10,387 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 16:47:10,431 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:48:37,849 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 16:48:37,914 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 16:48:37,917 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 16:48:37,969 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:49:21,775 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 16:49:25,406 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 16:49:25,444 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:49:26,859 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:49:26,919 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:54:44,951 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 16:54:58,239 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:54:58,278 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:54:58,317 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:54:59,261 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:54:59,278 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:54:59,310 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:54:59,791 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:54:59,815 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:54:59,836 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:55:00,245 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:55:00,263 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:55:00,292 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:55:28,545 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 16:55:34,398 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:55:34,500 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:55:34,537 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:57:55,137 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:57:55,216 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:57:55,249 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:57:55,981 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:57:56,071 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:57:56,086 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:57:56,478 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:57:56,556 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:57:56,587 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:57:56,667 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:57:56,742 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:57:56,762 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:57:56,826 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:57:57,007 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:57:57,040 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:57:59,477 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:57:59,549 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:57:59,574 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:57:59,702 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:57:59,773 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:57:59,806 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:57:59,997 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:58:00,074 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:58:00,098 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:58:32,905 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:58:32,984 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:58:33,013 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:58:33,581 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:58:33,689 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:58:33,690 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:58:37,416 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 16:58:39,166 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 16:58:39,274 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 16:58:39,303 - INFO - Usuario: aux | Rol: auxiliar  | GET /static/favicon.svg
2025-08-18 16:59:03,906 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 16:59:03,913 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 16:59:03,954 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:08:19,208 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:08:19,229 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:10:45,022 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 17:10:49,358 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:10:49,365 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 17:10:49,427 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:11:02,016 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 17:11:02,227 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:11:07,184 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 17:11:07,252 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:11:07,291 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:11:09,657 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 17:11:09,702 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:11:12,785 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:11:12,818 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:11:37,478 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 17:11:37,520 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:18:19,494 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 17:18:23,720 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:18:23,731 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:18:23,777 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:18:25,111 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:18:25,113 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:18:25,155 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:18:25,986 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:18:25,987 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:18:26,035 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:18:26,379 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:18:26,380 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:18:26,441 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:18:26,572 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:18:26,577 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:18:26,640 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:18:29,776 - INFO - Usuario: aux | Rol: auxiliar  | GET /
2025-08-18 17:18:29,808 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:18:34,120 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 17:18:34,197 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:18:34,198 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:18:34,254 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:22:02,807 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 17:22:12,783 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:22:12,831 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:23:06,971 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 17:23:07,113 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:23:26,703 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 17:23:29,069 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:23:29,089 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:23:31,543 - INFO - Usuario: aux | Rol: auxiliar  | GET /logout
2025-08-18 17:23:31,552 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 17:23:31,644 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:23:36,968 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 17:23:37,112 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:23:37,127 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:23:37,226 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:25:09,120 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:25:09,122 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:25:09,168 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:25:09,939 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:25:09,940 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:25:09,975 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:25:10,866 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:25:10,867 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 17:25:10,902 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:25:15,854 - INFO - Usuario: aux | Rol: auxiliar  | GET /
2025-08-18 17:25:15,917 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:25:27,458 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 17:25:30,403 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 17:25:30,437 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:25:30,551 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /static/favicon.svg
2025-08-18 17:25:36,132 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 17:25:36,268 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:25:36,283 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos1'. Did you mean 'inventario_articulos' instead?
2025-08-18 17:25:36,370 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:26:38,125 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 17:26:42,152 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:26:42,169 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos1'. Did you mean 'inventario_articulos' instead?
2025-08-18 17:26:42,222 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:26:43,020 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:26:43,021 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos1'. Did you mean 'inventario_articulos' instead?
2025-08-18 17:26:43,062 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:26:44,268 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:26:44,270 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos1'. Did you mean 'inventario_articulos' instead?
2025-08-18 17:26:44,325 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:26:59,556 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 17:27:01,677 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:27:01,691 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos1'. Did you mean 'inventario_articulos' instead?
2025-08-18 17:27:01,734 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:27:02,494 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:27:02,496 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos1'. Did you mean 'inventario_articulos' instead?
2025-08-18 17:27:02,547 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:27:03,542 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:27:03,543 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos1') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos1'. Did you mean 'inventario_articulos' instead?
2025-08-18 17:27:03,585 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 17:27:42,320 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 17:27:44,535 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 17:27:44,580 - INFO - Usuario: aux | Rol: auxiliar  | GET /.well-known/appspecific/com.chrome.devtools.json
2025-08-18 18:19:46,661 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 18:19:53,274 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:19:53,282 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 18:19:53,476 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /static/favicon.svg
2025-08-18 18:19:58,427 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 18:19:58,760 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:19:58,773 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario_articulos1' instead?
2025-08-18 18:19:58,893 - INFO - Usuario: aux | Rol: auxiliar  | GET /favicon.ico
2025-08-18 18:20:43,164 - INFO - Usuario: aux | Rol: auxiliar  | GET /
2025-08-18 18:20:45,413 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /inventarioequipos.
2025-08-18 18:20:49,239 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /inventarioequipos
2025-08-18 18:20:49,248 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 18:20:55,507 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /inventarioarticulo
2025-08-18 18:20:55,517 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 18:21:01,786 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 18:21:01,910 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:21:01,912 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario_articulos1' instead?
2025-08-18 18:21:06,485 - INFO - Usuario: aux | Rol: auxiliar  | GET /
2025-08-18 18:21:14,138 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /inventarioequipos
2025-08-18 18:21:14,146 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 18:22:43,022 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 18:22:47,752 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 18:22:47,902 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:22:47,920 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulos') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulos'. Did you mean 'inventario_articulos1' instead?
2025-08-18 18:23:39,701 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 18:23:41,538 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:23:43,911 - INFO - Usuario: aux | Rol: auxiliar  | GET /inventarioarticulo
2025-08-18 18:34:24,643 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 18:34:29,671 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:34:29,684 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 18:34:29,820 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /static/favicon.svg
2025-08-18 18:34:30,727 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /
2025-08-18 18:34:30,803 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | GET /static/favicon.svg
2025-08-18 18:34:36,405 - INFO - Usuario: ANÓNIMO | Rol: SIN ROL  | POST /
2025-08-18 18:34:36,623 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:34:36,651 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulo') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulo'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 18:34:40,149 - INFO - Usuario: aux | Rol: auxiliar  | POST /
2025-08-18 18:34:40,302 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:34:40,305 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 147, in top-level template code
    <a href="{{ url_for('inventario_articulo') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulo'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 18:40:18,495 - INFO - Serving on http://0.0.0.0:5000
2025-08-18 18:40:22,627 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:40:22,639 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 148, in top-level template code
    <a href="{{ url_for('inventario_articulo') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulo'. Did you mean 'inventario.inventario_articulo' instead?
2025-08-18 18:40:23,974 - INFO - Usuario: aux | Rol: auxiliar  | GET /home
2025-08-18 18:40:23,975 - ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\app.py", line 79, in home
    return render_template("home.html",
                           usuario=session["usuario"],
                           rol=session["rol"],
                           rol_id=session["rol_id"])
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\templates\home.html", line 148, in top-level template code
    <a href="{{ url_for('inventario_articulo') }}" class="text-decoration-none">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\juans\OneDrive\Documents\PROYECTOS\INVENTARIO\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inventario_articulo'. Did you mean 'inventario.inventario_articulo' instead?
